package network.backend



internal class FakeBackend : Backend{

    private val responses = mapOf(
        "products/userHighlighted" to "{\"category\":\"Feitos para Você\",\"products\":[{\"name\":\"Smartwatch Esportivo\",\"shortDescription\":\"Um smartwatch projetado para atividades esportivas com GPS e monitor de frequência cardíaca.\",\"price\":\"R\$ 199,99\"},{\"name\":\"Massageador Shiatsu\",\"shortDescription\":\"Um massageador elétrico com função de aquecimento para relaxamento muscular.\",\"price\":\"R\$ 79,99\"},{\"name\":\"Kit de Ferramentas\",\"shortDescription\":\"Um conjunto completo de ferramentas para pequenos reparos domésticos.\",\"price\":\"R\$ 49,99\"},{\"name\":\"Cafeteira Programável\",\"shortDescription\":\"Uma cafeteira com programação de preparo automático de café.\",\"price\":\"R\$ 129,99\"},{\"name\":\"Luminária de Mesa LED\",\"shortDescription\":\"Uma luminária de mesa com ajuste de intensidade e temperatura de cor.\",\"price\":\"R\$ 39,99\"},{\"name\":\"Mochila Tática\",\"shortDescription\":\"Uma mochila resistente com vários compartimentos e sistema de hidratação.\",\"price\":\"R\$ 89,99\"},{\"name\":\"Caixa de Som Bluetooth Portátil\",\"shortDescription\":\"Uma caixa de som compacta e à prova d'água para ouvir música em movimento.\",\"price\":\"R\$ 59,99\"},{\"name\":\"Pipoqueira Elétrica\",\"shortDescription\":\"Uma pipoqueira elétrica para preparar pipocas rápidas e saudáveis em casa.\",\"price\":\"R\$ 34,99\"}]}",
        "products/sale" to "{\"category\":\"Sale\",\"products\":[{\"name\":\"Smart TV 4K\",\"shortDescription\":\"Uma Smart TV com resolução 4K e acesso a vários aplicativos de streaming.\",\"price\":\"R\$ 1999,99\",\"oldPrice\":\"R\$ 2499,99\"},{\"name\":\"Fogão a Gás\",\"shortDescription\":\"Um fogão com quatro bocas e forno autolimpante.\",\"price\":\"R\$ 799,99\",\"oldPrice\":\"R\$ 899,99\"},{\"name\":\"Câmera DSLR\",\"shortDescription\":\"Uma câmera digital DSLR com lente intercambiável.\",\"price\":\"R\$ 1499,99\",\"oldPrice\":\"R\$ 1699,99\"},{\"name\":\"Console de Video Game\",\"shortDescription\":\"Um console de última geração com gráficos de alta definição.\",\"price\":\"R\$ 2399,99\",\"oldPrice\":\"R\$ 2799,99\"},{\"name\":\"Aspirador de Pó Robô\",\"shortDescription\":\"Um aspirador de pó inteligente que limpa automaticamente sua casa.\",\"price\":\"R\$ 699,99\",\"oldPrice\":\"R\$ 799,99\"},{\"name\":\"Panela de Pressão Elétrica\",\"shortDescription\":\"Uma panela de pressão elétrica com várias funções de cozimento.\",\"price\":\"R\$ 199,99\",\"oldPrice\":\"R\$ 219,99\"},{\"name\":\"Relógio Inteligente\",\"shortDescription\":\"Um relógio inteligente com monitor de atividades e notificações de smartphone.\",\"price\":\"R\$ 299,99\",\"oldPrice\":\"R\$ 349,99\"},{\"name\":\"Cadeira Ergonômica\",\"shortDescription\":\"Uma cadeira de escritório ergonômica com ajustes de altura e inclinação.\",\"price\":\"R\$ 449,99\",\"oldPrice\":\"R\$ 499,99\"},{\"name\":\"Máquina de Café Expresso\",\"shortDescription\":\"Uma máquina de café expresso com sistema de cápsulas.\",\"price\":\"R\$ 299,99\",\"oldPrice\":\"R\$ 349,99\"},{\"name\":\"Robô Aspirador de Pó\",\"shortDescription\":\"Um robô aspirador de pó inteligente com mapeamento de ambientes.\",\"price\":\"R\$ 899,99\",\"oldPrice\":\"R\$ 999,99\"}]}",
        "products/popular" to "{\"category\":\"Populares\",\"products\":[{\"name\":\"Smart TV 4K\",\"shortDescription\":\"Uma Smart TV com resolução 4K e acesso a vários aplicativos de streaming.\",\"price\":\"R\$ 1999,99\",\"oldPrice\":\"R\$ 2499,99\"},{\"name\":\"Fogão a Gás\",\"shortDescription\":\"Um fogão com quatro bocas e forno autolimpante.\",\"price\":\"R\$ 799,99\",\"oldPrice\":\"R\$ 899,99\"},{\"name\":\"Câmera DSLR\",\"shortDescription\":\"Uma câmera digital DSLR com lente intercambiável.\",\"price\":\"R\$ 1499,99\",\"oldPrice\":\"R\$ 1699,99\"},{\"name\":\"Console de Video Game\",\"shortDescription\":\"Um console de última geração com gráficos de alta definição.\",\"price\":\"R\$ 2399,99\",\"oldPrice\":\"R\$ 2799,99\"},{\"name\":\"Aspirador de Pó Robô\",\"shortDescription\":\"Um aspirador de pó inteligente que limpa automaticamente sua casa.\",\"price\":\"R\$ 699,99\",\"oldPrice\":\"R\$ 799,99\"},{\"name\":\"Panela de Pressão Elétrica\",\"shortDescription\":\"Uma panela de pressão elétrica com várias funções de cozimento.\",\"price\":\"R\$ 199,99\",\"oldPrice\":\"R\$ 219,99\"},{\"name\":\"Relógio Inteligente\",\"shortDescription\":\"Um relógio inteligente com monitor de atividades e notificações de smartphone.\",\"price\":\"R\$ 299,99\"},{\"name\":\"Headphone Bluetooth\",\"shortDescription\":\"Um headphone sem fio com cancelamento de ruído ativo.\",\"price\":\"R\$ 149,99\"},{\"name\":\"Monitor Curvo\",\"shortDescription\":\"Um monitor de computador curvo com resolução Full HD.\",\"price\":\"R\$ 999,99\"},{\"name\":\"Liquidificador Potente\",\"shortDescription\":\"Um liquidificador com motor de alta potência e várias velocidades.\",\"price\":\"R\$ 129,99\"}]}",
        "products/tech" to "{\"category\":\"Eletrônicos\",\"products\":[{\"name\":\"Smartphone XYZ\",\"shortDescription\":\"Um smartphone avançado com câmera de alta resolução.\",\"price\":\"R\$ 999,99\"},{\"name\":\"Fone de Ouvido Bluetooth ABC\",\"shortDescription\":\"Fone de ouvido sem fio com qualidade de som excepcional.\",\"price\":\"R\$ 79,99\"},{\"name\":\"Smartwatch ABC123\",\"shortDescription\":\"Um smartwatch com monitor de atividades e GPS integrado.\",\"price\":\"R\$ 149,99\"}]}",
        "products/health" to "{\"category\":\"Saúde\",\"products\":[{\"name\":\"Monitor de Pressão Arterial\",\"shortDescription\":\"Um monitor digital de pressão arterial para uso doméstico.\",\"price\":\"R\$ 129,99\"},{\"name\":\"Termômetro Digital\",\"shortDescription\":\"Um termômetro de alta precisão para medição rápida e confiável da temperatura corporal.\",\"price\":\"R\$ 39,99\"},{\"name\":\"Balança Digital\",\"shortDescription\":\"Uma balança de vidro temperado com tecnologia de precisão para medição de peso corporal.\",\"price\":\"R\$ 89,99\"},{\"name\":\"Inalador Nebulizador\",\"shortDescription\":\"Um nebulizador compacto e silencioso para tratamento de problemas respiratórios.\",\"price\":\"R\$ 199,99\"},{\"name\":\"Monitor de Glicose\",\"shortDescription\":\"Um medidor de glicose no sangue para controle preciso da diabetes.\",\"price\":\"R\$ 79,99\"},{\"name\":\"Kit Primeiros Socorros\",\"shortDescription\":\"Um conjunto completo de suprimentos para lidar com emergências médicas.\",\"price\":\"R\$ 59,99\"}]}"

    )

    override fun with(route: String) = responses[route]
}